spring.application.name=web-final
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/web_final
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA
spring.datasource.driver-class-name=org.postgresql.Driver

# IMPORTANTE: o schema já existe (criado via SQL). Deixe em 'none' ou 'validate'.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
